package com.example.data.repository

import com.example.domain.repository.OtpRepository
import com.example.services.OtpService
import org.litote.kmongo.coroutine.CoroutineDatabase

class OtpRepositoryImpl(
    private val db: CoroutineDatabase,
    private  val otpService: OtpService
): OtpRepository {

    override suspend fun saveOtp(target: String, otp: String, ttlMs: Long) {
        // ❌ Not needed anymore, handled by Twilio Verify
        throw UnsupportedOperationException("saveOtp is handled by Twilio Verify API")
    }

    override suspend fun verifyOtp(target: String, otp: String): Boolean {
        return otpService.verifyOtp(target, otp)
    }

    override suspend fun deliverOtp(target: String, otp: String) {
        // ❌ Not needed, OTP generated by Twilio Verify
        otpService.sendOtp(target)
    }
}